# mysql配置
addr: 127.0.0.1:3306 
user: root
pass: 910825
charset : utf8
slave_id: 1001 #slave ID
flavor: mysql #mysql or mariadb,默认mysql
gtid: true     # 是否使用Gtid复制，默认为false
ddl: true  #是否支持ddl语句,不支持表名映射或者字段名映射，即对象名须一致

#每批处理数量，不写默认100，可以根据带宽、机器性能等调整;如果是全量数据初始化时redis建议设为1000，其他接收端酌情调大
bulk_size: 3000 

#maxprocs: 10 #并发协（线）程数量，默认为: CPU核数*2；一般情况下不需要设置此项

#web admin相关配置
enable_web_admin: false #是否启用web admin，默认false
web_admin_port: 8060 #web监控端口,默认8060

#目标类型
target: mysql # 支持mysql、redis、mongodb、elasticsearch、rocketmq、kafka、rabbitmq

#目标mysql连接配置
mysql_addrs: 192.168.138.144:3306  
mysql_user: root
mysql_pass: 910825

#规则配置
rule:
  -
    schema: lxy #源数据库名称
    table: ll_info #源表名称,mysql、oracle、pg不支持同配符号
    order_by_column: lid #排序字段，存量数据同步时不能为空
    value_encoder: json  #值编码，支持json、kv-commas、v-commas；默认为json
    mysql_database: lxy #目标mysql的数据库名,必填
    mysql_table: ll_info  #目标mysql的表名,可以为空，默认使用源表名称
